env: 'production'

builtin: true

api:
  port: 9002

schedulers:
  - job: 'generate energy data daily at (07:25)'
    cron: '25 7 * * *'
    task:
      url: 'http://energy_core:9001/api/v1/device_output/generate/energy/daily'
      method: 'POST'
      body: >
        {"storeId": 0,"day": -1}
      # header: >
      #   {"X-Api-Key": "XXX"}

  - job: 'generate energy data monthly at (08:05)'
    cron: '5 8 * * *'
    task:
      url: 'http://energy_core:9001/api/v1/device_output/generate/energy/monthly'
      method: 'POST'
      body: >
        {"storeId": 0,"day": -1}
      # header: >
      #   {"X-Api-Key": "XXX"}
